export const GET_FOODS_START = 'GET_FOODS_START';
export const GET_FOODS_SUCCESS = 'GET_FOODS_SUCCESS';
export const GET_FOODS_ERROR = 'GET_FOODS_ERROR';

export const SAVE_FOOD_START = 'SAVE_FOOD_START';
export const SAVE_FOOD_SUCCESS = 'SAVE_FOOD_SUCCESS';
export const SAVE_FOOD_ERROR = 'SAVE_FOOD_ERROR';

export const UPDATE_FOOD_START = 'UPDATE_FOOD_START';
export const UPDATE_FOOD_SUCCESS = 'UPDATE_FOOD_SUCCESS';
export const UPDATE_FOOD_ERROR = 'UPDATE_FOOD_ERROR';

export const DELETE_FOOD_START = 'DELETE_FOOD_START';
export const DELETE_FOOD_SUCCESS = 'DELETE_FOOD_SUCCESS';
export const DELETE_FOOD_ERROR = 'DELETE_FOOD_ERROR';

//front client
export const CHANGE_FOOD_SELECTED = 'CHANGE_FOOD_SELECTED';
export const CHANGE_FOOD_TYPE_SELECTED = 'CHANGE_FOOD_TYPE_SELECTED';
export const SET_PORTIONS_SELECTED_FALSE = 'SET_PORTIONS_SELECTED_FALSE';
export const CHANGE_PORTION_SELECTED = 'CHANGE_PORTION_SELECTED';

//aditional
export const DELETE_PORTION = 'DELETE_PORTION';
export const ADD_LIST_PORTIONS = 'ADD_LIST_PORTIONS';
